#!/usr/bin/env python3
"""Generate catalog-seed.sql — the one-time bootstrap of the catalog store (ticket 02).

Joins the two authoritative sources and emits idempotent INSERT ... ON CONFLICT SQL:
  * kg-pipeline/manifest.jsonl            — the `done` docs (status, license, popularity)
  * data/programming-docs.db              — repo_url, version_label, is_latest, needs_human
      (programming_docs table, keyed by org/repo)

The immutable pin ({sha, docs_path, kg_ref}) and the savings numbers are NOT seeded —
they land later via POST /catalog/upsert once P1 (re-graphify from pinned HEADs) runs.
Only green-licensed docs are seeded `ready`; a non-green or needs_human doc is held
`provisional` and never served. Re-running (or re-seeding after P1) is safe: the ON
CONFLICT clauses refresh only the seed-owned columns and never clobber a filled-in pin.

Usage:  python3 backend/scripts/seed_catalog.py   # writes backend/catalog-seed.sql
Apply:  wrangler d1 execute docs-kg-catalog --file=catalog-seed.sql [--local|--remote]
"""
import json
import re
import sqlite3
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MANIFEST = REPO / "kg-pipeline" / "manifest.jsonl"
DB = REPO / "data" / "programming-docs.db"
OUT = REPO / "backend" / "catalog-seed.sql"
# Single source of truth for the green-license gate, shared with backend/src/license.ts.
GREEN = json.loads((REPO / "backend" / "src" / "green-licenses.json").read_text())


def is_green(license_id: str | None) -> bool:
    """The green allow-list (default-deny) — same rules as backend/src/license.ts,
    reading the same green-licenses.json so the seed and the runtime gate can't drift."""
    if not license_id:
        return False
    s = license_id.strip().upper()
    if any(x in s for x in GREEN["excludeIfContains"]):  # reject SA / NC / ND
        return False
    if s in GREEN["exact"]:
        return True
    return any(re.search(p, s) for p in GREEN["patterns"])


def q(v) -> str:
    """SQL literal: NULL, integer, or single-quoted string with quotes doubled."""
    if v is None:
        return "NULL"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def main() -> int:
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row

    docs_rows, version_rows = [], []
    ready = provisional = skipped = 0
    for line in MANIFEST.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        d = json.loads(line)
        if d.get("status") != "done":
            continue
        r = con.execute(
            "SELECT title, repo_url, version_label, needs_human, license_id "
            "FROM programming_docs WHERE org=? AND repo=?",
            (d["org"], d["repo"]),
        ).fetchone()
        if not r:
            skipped += 1
            print(f"  skip (no catalog row): {d['org']}/{d['repo']}", file=sys.stderr)
            continue

        slug = d["repo"]
        license_id = r["license_id"] or d.get("license_id")
        # Held provisional (never served) if the version label is unconfirmed OR the
        # license is not green; otherwise the done bundle seeds ready.
        held = bool(r["needs_human"]) or not is_green(license_id)
        status = "provisional" if held else "ready"
        ready += status == "ready"
        provisional += status == "provisional"

        docs_rows.append((slug, r["title"] or d.get("project") or slug, r["repo_url"], license_id, d["rank"]))
        # is_latest is OUR catalog's moving alias, not upstream's newest release: each
        # done doc has exactly one built KG, so that version is the latest we offer.
        # version_label still records the true built version (it may lag upstream — the
        # poller in ticket 09 builds the newer release and flips the alias then).
        version_rows.append(
            (slug, r["version_label"], 1, status, license_id, 1 if r["needs_human"] else 0)
        )

    lines = [
        "-- catalog-seed.sql — generated by backend/scripts/seed_catalog.py (ticket 02).",
        "-- Bootstrap of the launch catalog. Idempotent; pins/savings arrive later via /catalog/upsert.",
        "BEGIN TRANSACTION;",
    ]
    for slug, name, repo_url, lic, rank in docs_rows:
        lines.append(
            f"INSERT INTO docs (slug, name, repo_url, license_id, popularity_rank) "
            f"VALUES ({q(slug)}, {q(name)}, {q(repo_url)}, {q(lic)}, {q(rank)}) "
            f"ON CONFLICT(slug) DO UPDATE SET name=excluded.name, repo_url=excluded.repo_url, "
            f"license_id=excluded.license_id, popularity_rank=excluded.popularity_rank;"
        )
    for slug, vlabel, is_latest, status, lic, needs_human in version_rows:
        lines.append(
            f"INSERT INTO doc_versions (slug, version_label, is_latest, status, license_id, needs_human) "
            f"VALUES ({q(slug)}, {q(vlabel)}, {is_latest}, {q(status)}, {q(lic)}, {needs_human}) "
            f"ON CONFLICT(slug, version_label) DO UPDATE SET is_latest=excluded.is_latest, "
            f"status=excluded.status, license_id=excluded.license_id, needs_human=excluded.needs_human;"
        )
    lines.append("COMMIT;")
    OUT.write_text("\n".join(lines) + "\n")

    print(
        f"wrote {OUT.relative_to(REPO)}: {len(docs_rows)} docs "
        f"({ready} ready, {provisional} provisional, {skipped} skipped)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
